[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
via_ir = true

remappings = [
    "forge-std/=dependencies/forge-std-1.11.0/src/"
]

[dependencies]
forge-std = "1.11.0"

[rpc_endpoints]
ETH = "${ETH_RPC_URL}"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
